extends Node

var IN_MENU = true
var ALLOW_MOVEMENT = true
var RESTRAIN_SCREEN = false
var IN_GAME = false
var GAME_FALLING = false

#var SCREEN_SIZE_X = 1920#576
#var SCREEN_SIZE_Y = 1080#324
var SCREEN_SIZE_X = 576
var SCREEN_SIZE_Y = 324

var HIGHEST_LEVEL = 0
var CURRENT_LEVEL = 0

var PLAYER_COINS = 0
var PLAYER_MAX_HEALTH = 400
var PLAYER_SHOOTING_SPD = 1000
var PLAYER_SHOOTING_INTERVAL = 0.2
var PLAYER_SHOOTING_LIFETIME = 0.4
var PLAYER_DAMAGE = 100
var TOTAL_DEATHS = 0

var LEVEL_1_1_AQUIRED = false
var LEVEL_1_2_AQUIRED = false
var LEVEL_2_1_AQUIRED = false
var LEVEL_2_2_AQUIRED = false
